services:
  lunch-menu-bot:
    build: .
    container_name: lunch-menu-bot
    restart: unless-stopped
    volumes:
      - ./.secrets:/app/.secrets:ro
    environment:
      - RUN_SLACK=true  # Set to "true" to enable Slack integration
      - RUN_DISCORD=true  # Set to "true" to enable Discord bot
